version: '3'

services:
  api:
    container_name: api
    image: docker.io/bitnami/wildfly:30
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/hospital"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "123kaike123"
      WILDFLY_USERNAME: "adminwildfly"
      WILDFLY_PASSWORD: "adminwildfly"
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - .\deploy:/opt/bitnami/wildfly/standalone/deployments
    depends_on:
      - postgres
    networks:
      - mynetwork
    restart: always

  postgres:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - .\database\data:/var/lib/postgresql/data
      - .\sql\data.sql:/docker-entrypoint-initdb.d/01-basegeografica.sql
      - .\sql\pg_hba.conf:/etc/postgresql/pg_hba.conf
#      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - mynetwork
    restart: always
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "kaike@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "8082:80"
    depends_on:
      - postgres
    networks:
      - mynetwork
    restart: always

networks: 
  mynetwork:  
    driver: bridge  