version: '3'

services:
  api:
    container_name: api
    image: bitnami/wildfly
    environment:
      DATABASE_URL: "jdbc:postgresql://hospital:5432/hospital"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      WILDFLY_USERNAME: "admin"
      WILDFLY_PASSWORD: "admin"
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - .C:\wildfly\standalone\deployments:/opt/bitnami/wildfly/standalone/deployments
    depends_on:
      - postgres
    networks:
      - default
    restart: always

  postgres:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - .\database\data:/var/lib/postgresql/data
#      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
#      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - default
    restart: always
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "kaike@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "8082:80"
    depends_on:
      - postgres
    networks:
      - default
    restart: always

networks: 
  default:
    name: rede
